README for Needlet_decomp
=========================

Introduction
------------
This repository contains the source code for a C++ program which decomposes
HEALPix scalar maps into their needlet components.

Supported platforms
-------------------

The program has been developed on Mac OS X 10.6, but it should run on any
Unix machine.

Installation
------------

Before compiling the software, you have to install the following
components:

- http://www.cs.tufts.edu/~nr/noweb/[Noweb], a tool for literate
  programming by Norman Ramsey

- http://www.gnu.org/software/gsl/[The GNU Scientific Library] (GSL)

- http://sourceforge.net/projects/healpix/[Healpix] (at least version
  2.20a -- any version older than this will produce compilation
  errors).

- http://www.r-project.org/[GNU R], to create the nice plot showing needlets in
  harmonic space.

It is likely that you can install both Noweb and GSL using your
favourite package manager (e.g. `apt-get` on Ubuntu Linux).

After you installed the dependencies, run `configure` and then `make`. Note that
if you are using a version of Healpix that has been compiled with
OpenMP support enabled (chances are: yes, you are), then you must invoke
`configure` with the `--with-openmp` flag. Call `configure --help` for
more options.